version: '3.7'
services:
    mgsis:
        build:
            './.docker'
        volumes:
            - /opt/www:/opt/www
            - /tmp:/tmp/host
            - .docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - /media/publico:/media/publico
        ports:
            - "9000:9000"
