version: '3.7'
services:
    mgsis:
        build: ./
        restart: unless-stopped
        volumes:
            - /opt/www:/opt/www
            - /tmp:/tmp/host
            - ./php.ini:/usr/local/etc/php/php.ini
            - /media/publico:/media/publico
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
            - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "sistema.mgpapelaria.com.br:host-gateway"
            - "api.mgspa.mgpapelaria.com.br:host-gateway"
            - "api-mgspa.mgpapelaria.com.br:host-gateway"
            - "api-mgspa-dev.mgpapelaria.com.br:host-gateway"
            - "mgspa.mgpapelaria.com.br:host-gateway"
        ports:
            - "9000:9000"
