<?php

class m131118_181943_cria_campos_criacao_alteracao extends CDbMigration
{
	public function up()
	{
		// cria campo alteracao
		Yii::app()->db->createCommand('alter table tblfilial add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblportador add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestado add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblpais add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblecf add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblncm add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add alteracao TIMESTAMP WITHOUT TIME ZONE')->execute();
	
		//cria campo codusuarioalteracao
		Yii::app()->db->createCommand('alter table tblfilial add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblportador add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestado add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblpais add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblecf add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcheque add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add codusuarioalteracao BIGINT')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblncm add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add codusuarioalteracao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add codusuarioalteracao BIGINT')->execute();
		
		//cria chave estrangeira para codusuarioalteracao
		Yii::app()->db->createCommand('alter table tblfilial add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblportador add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestado add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblpais add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblecf add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcheque add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblncm add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add foreign key (codusuarioalteracao) references tblusuario (codusuario)')->execute();

		//cria campo criacao
		Yii::app()->db->createCommand('alter table tblfilial add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblportador add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestado add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblpais add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblecf add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcheque add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblncm add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add criacao TIMESTAMP WITHOUT TIME ZONE')->execute();

		//cria campo codusuariocriacao
		Yii::app()->db->createCommand('alter table tblfilial add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblportador add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestado add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblpais add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblecf add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcheque add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add codusuariocriacao BIGINT')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblncm add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add codusuariocriacao BIGINT')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add codusuariocriacao BIGINT')->execute();
		
		//cria chave estrangeira para codusuariocriacao
		Yii::app()->db->createCommand('alter table tblfilial add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblusuario add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblportador add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblempresa add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestado add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblproduto add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblpais add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblecf add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcheque add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblbanco add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcidade add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblncm add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblsexo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcfop add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmenu add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblmarca add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblibptax add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco add foreign key (codusuariocriacao) references tblusuario (codusuario)')->execute();
		
	}

	public function down()
	{
		
		//exclui coluna alteracao
		Yii::app()->db->createCommand('alter table tblfilial drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblusuario drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblportador drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblempresa drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestado drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblproduto drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblpais drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblecf drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblbanco drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcidade drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem drop column alteracao')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblncm drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblsexo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcfop drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmenu drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmarca drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblibptax drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto drop column alteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco drop column alteracao')->execute();
		
		//exclui coluna codusuarioalteracao
		Yii::app()->db->createCommand('alter table tblfilial drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblusuario drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblportador drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblempresa drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestado drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblproduto drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblpais drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblecf drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcheque drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblbanco drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcidade drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem drop column codusuarioalteracao')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblncm drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblsexo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcfop drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmenu drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblmarca drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblibptax drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto drop column codusuarioalteracao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco drop column codusuarioalteracao')->execute();

		//exclui coluna criacao
		Yii::app()->db->createCommand('alter table tblfilial drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblusuario drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblportador drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblempresa drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestado drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblproduto drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblpais drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblecf drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcheque drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblbanco drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcidade drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem drop column criacao')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblncm drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblsexo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcfop drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblmenu drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblmarca drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblibptax drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto drop column criacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco drop column criacao')->execute();
		
		//exclui coluna codusuariocriacao
		Yii::app()->db->createCommand('alter table tblfilial drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblmovimentotitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblusuario drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblportador drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblpessoa drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltituloagrupamento drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblliquidacaotitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipomovimentotitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobranca drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletoretorno drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblempresa drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestado drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblproduto drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutobarra drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimentotipo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscalprodutobarra drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalprodutobarra drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblpais drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblecfreducaoz drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblecf drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcupomfiscal drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistoricotitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcobrancahistorico drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcheque drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblbanco drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblchequeemitente drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcidade drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutoembalagem drop column codusuariocriacao')->execute();
		//Yii::app()->db->createCommand('alter table tblauditoriatransmissao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbloperacao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblunidademedida drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacaonaturezaoperacao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipoproduto drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblparametrosgerais drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblncm drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnaturezaoperacao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquemovimento_2012 drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblsexo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestadocivil drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalduplicatas drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscalcartacorrecao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcfop drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblmenu drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioprodutobarra drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegociostatus drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocioformapagamento drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnegocio drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblnotafiscal drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltributacao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblestoquesaldo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletomotivoocorrencia drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblboletotipoocorrencia drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcodigo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblgrupoproduto drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblmarca drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblibptax drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblformapagamento drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblbaseremota drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tbltipotitulo drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblcontacontabil drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoriaexcecao drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblauditoria drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblsubgrupoproduto drop column codusuariocriacao')->execute();
		Yii::app()->db->createCommand('alter table tblprodutohistoricopreco drop column codusuariocriacao')->execute();
		
	}

	/*
	// Use safeUp/safeDown to do migration with transaction
	public function safeUp()
	{
	}

	public function safeDown()
	{
	}
	 * 
	 */
	
}