<?php
$this->pagetitle = Yii::app()->name . ' - Detalhes do Negócio';
$this->breadcrumbs=array(
	'Negócios'=>array('index'),
	$model->codnegocio,
);

$this->menu=array(
array('label'=>'Listagem (F1)', 'icon'=>'icon-list-alt', 'url'=>array('index')),
array('label'=>'Novo (F2)', 'icon'=>'icon-plus', 'url'=>array('create')),
array('label'=>'Fechar Negócio (F3)', 'icon'=>'icon-pencil', 'url'=>array('update','id'=>$model->codnegocio), 'visible'=>($model->codnegociostatus==1), 'linkOptions'=>	array('id'=>'btnFechar')),
array('label'=>'Excluir', 'icon'=>'icon-trash', 'url'=>'#', 'linkOptions'=>	array('id'=>'btnExcluir')),
//array('label'=>'Gerenciar', 'icon'=>'icon-briefcase', 'url'=>array('admin')),
);

Yii::app()->clientScript->registerCoreScript('yii');
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/jquery.hotkeys.js');

?>

<script type="text/javascript">
/*<![CDATA[*/
$(document).ready(function(){
	$('body').on('click','#btnExcluir',function() {
		bootbox.confirm("Excluir este registro?", function(result) {
			if (result)
				jQuery.yii.submitForm(document.body.childNodes[0], "<?php echo Yii::app()->createUrl('negocio/delete', array('id' => $model->codnegocio))?>",{});
		});
	});
	
	$(document).bind('keydown.f1',function (e){
		$('#btnFechar').trigger('click');
		window.location = '<?php echo Yii::app()->createUrl('negocio/index')?>';
		return false; 
	});
	$(document).bind('keydown.f2',function (e){
		$('#btnFechar').trigger('click');
		window.location = '<?php echo Yii::app()->createUrl('negocio/create')?>';
		return false; 
	});
	$(document).bind('keydown.f3',function (e){
		$('#btnFechar').trigger('click');
		window.location = '<?php echo Yii::app()->createUrl('negocio/update', array('id' => $model->codnegocio))?>';
		return false; 
	});
	//$("#barras").bind('keydown.Alt_f',function (e){e.preventDefault(); alert('#Alt_f'); return false; });
	
	
});
/*]]>*/
</script>

<script>
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo(){
		/*
		jQuery('#platform-details').html('<code>' + navigator.userAgent + '</code>');
		jQuery(document).bind('keydown.esc',function (evt){alert("esc"); return false; });
		jQuery(document).bind('keydown.tab',function (evt){jQuery('#_tab').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.space',function (evt){jQuery('#_space').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.return',function (evt){jQuery('#_return').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.backspace',function (evt){jQuery('#_backspace').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.scroll',function (evt){jQuery('#_scroll').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.capslock',function (evt){jQuery('#_capslock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.numlock',function (evt){jQuery('#_numlock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.pause',function (evt){jQuery('#_pause').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.insert',function (evt){jQuery('#_insert').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.home',function (evt){jQuery('#_home').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.del',function (evt){jQuery('#_del').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.end',function (evt){jQuery('#_end').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.pageup',function (evt){jQuery('#_pageup').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.pagedown',function (evt){jQuery('#_pagedown').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.left',function (evt){jQuery('#_left').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.up',function (evt){jQuery('#_up').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.right',function (evt){jQuery('#_right').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.down',function (evt){jQuery('#_down').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f1',function (evt){jQuery('#_f1').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f2',function (evt){jQuery('#_f2').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f3',function (evt){jQuery('#_f3').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f4',function (evt){jQuery('#_f4').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f5',function (evt){jQuery('#_f5').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f6',function (evt){jQuery('#_f6').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f7',function (evt){jQuery('#_f7').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f8',function (evt){jQuery('#_f8').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f9',function (evt){jQuery('#_f9').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f10',function (evt){jQuery('#_f10').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f11',function (evt){jQuery('#_f11').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f12',function (evt){jQuery('#_f12').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.1',function (evt){jQuery('#_1').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.2',function (evt){jQuery('#_2').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.3',function (evt){jQuery('#_3').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.4',function (evt){jQuery('#_4').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.5',function (evt){jQuery('#_5').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.6',function (evt){jQuery('#_6').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.7',function (evt){jQuery('#_7').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.8',function (evt){jQuery('#_8').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.9',function (evt){jQuery('#_9').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.0',function (evt){jQuery('#_0').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.a',function (evt){jQuery('#_a').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.b',function (evt){jQuery('#_b').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.c',function (evt){jQuery('#_c').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.d',function (evt){jQuery('#_d').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.e',function (evt){jQuery('#_e').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.f',function (evt){jQuery('#_f').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.g',function (evt){jQuery('#_g').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.h',function (evt){jQuery('#_h').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.i',function (evt){jQuery('#_i').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.j',function (evt){jQuery('#_j').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.k',function (evt){jQuery('#_k').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.l',function (evt){jQuery('#_l').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.m',function (evt){jQuery('#_m').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.n',function (evt){jQuery('#_n').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.o',function (evt){jQuery('#_o').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.p',function (evt){jQuery('#_p').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.q',function (evt){jQuery('#_q').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.r',function (evt){jQuery('#_r').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.s',function (evt){jQuery('#_s').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.t',function (evt){jQuery('#_t').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.u',function (evt){jQuery('#_u').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.v',function (evt){jQuery('#_v').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.w',function (evt){jQuery('#_w').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.x',function (evt){jQuery('#_x').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.y',function (evt){jQuery('#_y').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.z',function (evt){jQuery('#_z').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_a',function (evt){jQuery('#_Ctrl_a').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_b',function (evt){jQuery('#_Ctrl_b').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_c',function (evt){jQuery('#_Ctrl_c').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_d',function (evt){jQuery('#_Ctrl_d').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_e',function (evt){jQuery('#_Ctrl_e').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f',function (evt){jQuery('#_Ctrl_f').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_g',function (evt){jQuery('#_Ctrl_g').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_h',function (evt){jQuery('#_Ctrl_h').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_i',function (evt){jQuery('#_Ctrl_i').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_j',function (evt){jQuery('#_Ctrl_j').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_k',function (evt){jQuery('#_Ctrl_k').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_l',function (evt){jQuery('#_Ctrl_l').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_n',function (evt){jQuery('#_Ctrl_n').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_o',function (evt){jQuery('#_Ctrl_o').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_p',function (evt){jQuery('#_Ctrl_p').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_q',function (evt){jQuery('#_Ctrl_q').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_r',function (evt){jQuery('#_Ctrl_r').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_s',function (evt){jQuery('#_Ctrl_s').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_t',function (evt){jQuery('#_Ctrl_t').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_u',function (evt){jQuery('#_Ctrl_u').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_v',function (evt){jQuery('#_Ctrl_v').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_w',function (evt){jQuery('#_Ctrl_w').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_x',function (evt){jQuery('#_Ctrl_x').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_y',function (evt){jQuery('#_Ctrl_y').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_z',function (evt){jQuery('#_Ctrl_z').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_a',function (evt){jQuery('#_Shift_a').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_b',function (evt){jQuery('#_Shift_b').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_c',function (evt){jQuery('#_Shift_c').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_d',function (evt){jQuery('#_Shift_d').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_e',function (evt){jQuery('#_Shift_e').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f',function (evt){jQuery('#_Shift_f').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_g',function (evt){jQuery('#_Shift_g').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_h',function (evt){jQuery('#_Shift_h').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_i',function (evt){jQuery('#_Shift_i').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_j',function (evt){jQuery('#_Shift_j').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_k',function (evt){jQuery('#_Shift_k').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_l',function (evt){jQuery('#_Shift_l').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_m',function (evt){jQuery('#_Shift_m').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_n',function (evt){jQuery('#_Shift_n').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_o',function (evt){jQuery('#_Shift_o').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_p',function (evt){jQuery('#_Shift_p').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_q',function (evt){jQuery('#_Shift_q').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_r',function (evt){jQuery('#_Shift_r').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_s',function (evt){jQuery('#_Shift_s').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_t',function (evt){jQuery('#_Shift_t').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_u',function (evt){jQuery('#_Shift_u').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_v',function (evt){jQuery('#_Shift_v').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_w',function (evt){jQuery('#_Shift_w').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_x',function (evt){jQuery('#_Shift_x').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_y',function (evt){jQuery('#_Shift_y').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_z',function (evt){jQuery('#_Shift_z').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_a',function (evt){jQuery('#_Alt_a').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_b',function (evt){jQuery('#_Alt_b').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_c',function (evt){jQuery('#_Alt_c').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_d',function (evt){jQuery('#_Alt_d').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_e',function (evt){jQuery('#_Alt_e').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f',function (evt){jQuery('#_Alt_f').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_g',function (evt){jQuery('#_Alt_g').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_h',function (evt){jQuery('#_Alt_h').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_i',function (evt){jQuery('#_Alt_i').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_j',function (evt){jQuery('#_Alt_j').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_k',function (evt){jQuery('#_Alt_k').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_l',function (evt){jQuery('#_Alt_l').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_m',function (evt){jQuery('#_Alt_m').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_n',function (evt){jQuery('#_Alt_n').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_o',function (evt){jQuery('#_Alt_o').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_p',function (evt){jQuery('#_Alt_p').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_q',function (evt){jQuery('#_Alt_q').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_r',function (evt){jQuery('#_Alt_r').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_s',function (evt){jQuery('#_Alt_s').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_t',function (evt){jQuery('#_Alt_t').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_u',function (evt){jQuery('#_Alt_u').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_v',function (evt){jQuery('#_Alt_v').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_w',function (evt){jQuery('#_Alt_w').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_x',function (evt){jQuery('#_Alt_x').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_y',function (evt){jQuery('#_Alt_y').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_z',function (evt){jQuery('#_Alt_z').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_esc', function (evt){jQuery('#_Ctrl_esc').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_tab', function (evt){jQuery('#_Ctrl_tab').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_space', function (evt){jQuery('#_Ctrl_space').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_return', function (evt){jQuery('#_Ctrl_return').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_backspace', function (evt){jQuery('#_Ctrl_backspace').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_scroll', function (evt){jQuery('#_Ctrl_scroll').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_capslock', function (evt){jQuery('#_Ctrl_capslock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_numlock', function (evt){jQuery('#_Ctrl_numlock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_pause', function (evt){jQuery('#_Ctrl_pause').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_insert', function (evt){jQuery('#_Ctrl_insert').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_home', function (evt){jQuery('#_Ctrl_home').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_del', function (evt){jQuery('#_Ctrl_del').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_end', function (evt){jQuery('#_Ctrl_end').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_pageup', function (evt){jQuery('#_Ctrl_pageup').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_pagedown', function (evt){jQuery('#_Ctrl_pagedown').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_left', function (evt){jQuery('#_Ctrl_left').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_up', function (evt){jQuery('#_Ctrl_up').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_right', function (evt){jQuery('#_Ctrl_right').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_down', function (evt){jQuery('#_Ctrl_down').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f1', function (evt){jQuery('#_Ctrl_f1').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f2', function (evt){jQuery('#_Ctrl_f2').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f3', function (evt){jQuery('#_Ctrl_f3').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f4', function (evt){jQuery('#_Ctrl_f4').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f5', function (evt){jQuery('#_Ctrl_f5').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f6', function (evt){jQuery('#_Ctrl_f6').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f7', function (evt){jQuery('#_Ctrl_f7').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f8', function (evt){jQuery('#_Ctrl_f8').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f9', function (evt){jQuery('#_Ctrl_f9').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f10', function (evt){jQuery('#_Ctrl_f10').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f11', function (evt){jQuery('#_Ctrl_f11').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Ctrl_f12', function (evt){jQuery('#_Ctrl_f12').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_esc', function (evt){jQuery('#_Shift_esc').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_tab', function (evt){jQuery('#_Shift_tab').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_space', function (evt){jQuery('#_Shift_space').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_return', function (evt){jQuery('#_Shift_return').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_backspace', function (evt){jQuery('#_Shift_backspace').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_scroll', function (evt){jQuery('#_Shift_scroll').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_capslock', function (evt){jQuery('#_Shift_capslock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_numlock', function (evt){jQuery('#_Shift_numlock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_pause', function (evt){jQuery('#_Shift_pause').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_insert', function (evt){jQuery('#_Shift_insert').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_home', function (evt){jQuery('#_Shift_home').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_del', function (evt){jQuery('#_Shift_del').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_end', function (evt){jQuery('#_Shift_end').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_pageup', function (evt){jQuery('#_Shift_pageup').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_pagedown', function (evt){jQuery('#_Shift_pagedown').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_left', function (evt){jQuery('#_Shift_left').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_up', function (evt){jQuery('#_Shift_up').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_right', function (evt){jQuery('#_Shift_right').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_down', function (evt){jQuery('#_Shift_down').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f1', function (evt){jQuery('#_Shift_f1').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f2', function (evt){jQuery('#_Shift_f2').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f3', function (evt){jQuery('#_Shift_f3').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f4', function (evt){jQuery('#_Shift_f4').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f5', function (evt){jQuery('#_Shift_f5').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f6', function (evt){jQuery('#_Shift_f6').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f7', function (evt){jQuery('#_Shift_f7').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f8', function (evt){jQuery('#_Shift_f8').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f9', function (evt){jQuery('#_Shift_f9').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f10', function (evt){jQuery('#_Shift_f10').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f11', function (evt){jQuery('#_Shift_f11').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Shift_f12', function (evt){jQuery('#_Shift_f12').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_esc', function (evt){jQuery('#_Alt_esc').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_tab', function (evt){jQuery('#_Alt_tab').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_space', function (evt){jQuery('#_Alt_space').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_return', function (evt){jQuery('#_Alt_return').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_backspace', function (evt){jQuery('#_Alt_backspace').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_scroll', function (evt){jQuery('#_Alt_scroll').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_capslock', function (evt){jQuery('#_Alt_capslock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_numlock', function (evt){jQuery('#_Alt_numlock').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_pause', function (evt){jQuery('#_Alt_pause').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_insert', function (evt){jQuery('#_Alt_insert').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_home', function (evt){jQuery('#_Alt_home').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_del', function (evt){jQuery('#_Alt_del').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_end', function (evt){jQuery('#_Alt_end').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_pageup', function (evt){jQuery('#_Alt_pageup').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_pagedown', function (evt){jQuery('#_Alt_pagedown').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_left', function (evt){jQuery('#_Alt_left').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_up', function (evt){jQuery('#_Alt_up').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_right', function (evt){jQuery('#_Alt_right').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_down', function (evt){jQuery('#_Alt_down').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f1', function (evt){jQuery('#_Alt_f1').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f2', function (evt){jQuery('#_Alt_f2').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f3', function (evt){jQuery('#_Alt_f3').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f4', function (evt){jQuery('#_Alt_f4').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f5', function (evt){jQuery('#_Alt_f5').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f6', function (evt){jQuery('#_Alt_f6').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f7', function (evt){jQuery('#_Alt_f7').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f8', function (evt){jQuery('#_Alt_f8').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f9', function (evt){jQuery('#_Alt_f9').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f10', function (evt){jQuery('#_Alt_f10').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f11', function (evt){jQuery('#_Alt_f11').addClass('dirty'); return false; });
		jQuery(document).bind('keydown.Alt_f12', function (evt){jQuery('#_Alt_f12').addClass('dirty'); return false; });
		*/
	}


	jQuery(document).ready(domo);
	
	

</script>


<div class="row-fluid">

	<div class="span8">
		<?php
			$this->widget(
				'bootstrap.widgets.TbTabs',
				array(
					'type' => 'tabs', // 'tabs' or 'pills'
					'tabs' => array(
						array(
							'label' => 'Produtos',
							'content' => $this->renderPartial('_view_produtos', array('model'=>$model), true),
							'active' => true
						),
						array(
							'label' => 'Documentos', 
							'content' => 'Ainda Vazio'
						),
					),
				)
			);	
		?>
	</div>
	
	<div class="span4">

		<?php if ($model->codnegociostatus == 3): ?>
			<div class="alert alert-danger">
				<b>Cancelado em <?php echo CHtml::encode((empty($model->alteracao)?$model->lancamento:$model->alteracao)); ?> </b>
			</div>
		<?php endif; ?>

		<div id="totais">
			<?php $this->renderPartial('_view_totais', array('model'=>$model));	?>
		</div>
		
		<?php 
		$this->widget('bootstrap.widgets.TbDetailView',array(
			'data'=>$model,
			'attributes'=>array(
				array(
					'name'=>'codnegocio',
					'value'=> Yii::app()->format->formataCodigo($model->codnegocio),
					),
				array(
					'name'=>'codnaturezaoperacao',
					'value'=>
						((isset($model->Operacao))?$model->Operacao->operacao:null)
						. " - " .
						((isset($model->NaturezaOperacao))?$model->NaturezaOperacao->naturezaoperacao:null),
					),
				array(
					'name'=>'codpessoa',
					'value'=>(isset($model->Pessoa))?CHtml::link(CHtml::encode($model->Pessoa->fantasia),array('pessoa/view','id'=>$model->codpessoa)):null,
					'type'=>'raw',
					),
				array(
					'name'=>'codpessoavendedor',
					'value'=>(isset($model->PessoaVendedor))?$model->PessoaVendedor->fantasia:null,
					),
				'lancamento',
				array(
					'name'=>'codnegociostatus',
					'value'=>(isset($model->NegocioStatus))?$model->NegocioStatus->negociostatus:null,
					),
				array(
					'name'=>'codfilial',
					'value'=>(isset($model->Filial))?$model->Filial->filial:null,
					),
				array(
					'name'=>'codusuario',
					'value'=>(isset($model->Usuario))?$model->Usuario->usuario:null,
					),
				'observacoes',
				),
			)); 
		
			
			$this->widget('UsuarioCriacao', array('model'=>$model));

		?>
	</div>
</div>